### PR TITLE
DIG-1371 Tax does not match Spree

### PR DESCRIPTION
**Pull request by fernando-barajas**
The logic to calculate the order discounts is not taking under consideration all the adjustments of the order (e.g. Shipment discount), also if the order includes a not eligible discount it gets through Avalara.
- Include all eligible adjustments of the order in the data sent to avalara.

### CODE REVIEW

**Comment by fernando-barajas** [comment]
@tomfbiz could you code review this PR?

**Comment by tomfbiz** [comment]
I did not test this but I have a couple of comments --
1. I see that we went from  calculating tax on docs of type SalesOrder to type of SalesOrder or SailsInvoice. Is this by design and intentional? I don't want us to tell Avalara that we paid taxes for something we only invoiced. On the other hand, we do want to show the taxes in gthe invoice. I'm not sure exactly how this works currently or what was not working.
2. There were two tickets related to taxes and promos that I worked on in January 2016:
   https://github.com/littlebitselectronics/spree_avatax/pull/1/files
   https://github.com/littlebitselectronics/little_bits/pull/2969
   We need to make sure that we are not double counting the promos now.

We should make sure to test the scenario that these were addressing (adding "lights" promo to the cart did not discount the tax on the free items). You or @tsouthworth-lb should change the end-date on that promo in staging and make sure your change did not impact it.

**Comment by fernando-barajas** [comment]
@tomfbiz thanks for review this PR, about your comments:

1.- We have been calculating taxes for both docs, this update is to make sure that if something has been changed with the order (e.g. a promotion is not longer eligible for the order) when the order is in payment state and the customer clicks on "Place Order" button, the Spree::Tax adjustment of the order got updated.

2.- Not all adjustments are sent to Avatax, e.g. adjustments created on Admin's page or the total of free items. What this update does is to include all the eligible adjustments of the order as part of the "Discount" field sent to Avalara.

image

image

Regards.

**Comment by tomfbiz** [comment]
This looks good. OK to merge, if @tsouthworth-lb has QA'ed (I did not QA, just reviewed the code).

**Pull request merged**
